### ISSUE TITLE
Script fails in Linux

### ISSUE THREAD

**Issue by ACXgit** [tivac/mithril-objectify#19]
I've run in a similar issue:
https://github.com/nwjs/nw-builder/issues/75
I noticed that many files have Dos\Windows EOL while they should have UNIX EOL.

**Comment by tivac** [comment]
Looks like npm/npm#2097 strikes again.

**Comment by tivac** [comment]
@ACXgit `mithril-objectify@1.2.2` **should** have the correct line-endings in `/bin/cli.js`.

I only have a windows box though, so let me know if that doesn't solve it.

**Comment by ACXgit** [comment]
I confirm that it's ok now :+1:

**Comment by HendrikRoth** [comment]
This fix works only loading mithril-objectify direct via git. The npm package still fails.

**Comment by tivac** [comment]
Opened #30 to set up publishing via Travis, which should solve this. Sorry about that!

**Comment by tivac** [comment]
I just published `mithril-objectify@2.2.1` via travis, @HendrikRoth would you give it another shot?

**Comment by HendrikRoth** [comment]
Confirmed. Can be closed!
