### ISSUE TITLE
Allow to use it without babel

### ISSUE THREAD

**Issue by StephanHoyer** [tivac/mithril-objectify#34]
Hi Tivac.

Loved you module so far. Now as it requires babel to run not so much.

Would love allow to use it as plain browserify transform again.

**Comment by tivac** [comment]
`2.2.5` still works fine if you're really dead-set against babel. I like having reasonable source maps (falafel provided zero options there) and it's trivial to use babel w/o all the ES2015 -> ES5 plugins if you want.

**Comment by StephanHoyer** [comment]
I'm afraid future optimisations will not be backported. I'm fine with ver 2.2.5.

I use mithril-objectify only in production/staging and not in develop. Thats why lack of sourcemaps are no issue for me.

Thanks for your work anyways.

**Comment by tivac** [comment]
Installing `babelify` and using `mithril-objectify` as the only babel plugin you run in it is pretty simple to do. It also means that I don't have to support a browserify/rollup/webpack/etc transform, since that work is already done by other people :smile:

**Comment by StephanHoyer** [comment]
Tools can break. More tools, higher probability that something breaks... So I just use Browserify (the API in a express-server not commandline) and Uglify (for production). I try to keep things as simple as possible. I once tried babel. It has a hell of dependencies. Hopefully I never need this.
